spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://mysql-service:3306/mydatabase
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
